---
name: prophet-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - fbprophet
  - pip:
      - pandas
      - schedule
      - prometheus_api_client
      - tornado
      - dateparser
      - numpy
      - pyyaml
      - holidays