settings:
  prometheus:
    url: http://demo.robustperception.io:9090/
params:
  three_weeks:
    retraining_interval: 6h
    training_window: 21d    
    resolution: 30m
    daily_seasonality: true
  three_months:
    training_window: 90d
    resolution: 1d
model_templates:
  alertmanager:
    saturation:
      expr: sum(irate(alertmanager_http_request_duration_seconds_count[5m]))
      params: three_weeks
      fill_na: zeros
    latency:
      expr: sum(irate(alertmanager_http_request_duration_seconds_sum[5m])) / sum(irate(alertmanager_http_request_duration_seconds_count[5m]))
      params: three_months
  prometheus:
    counter:
      expr: prometheus_http_request_duration_seconds_count{handler=~'/alerts|/config'}
      params: three_weeks
